### ISSUE TITLE
CAA records

### ISSUE THREAD

**Issue by sledz** [yast/yast-dns-server#66]
Any plans to add support for [CAA records](https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization)?

**Comment by dgdavid** [comment]
Hi @sledz 

Please, excuse us for having missed the issue until now.

If you still interested, could you open a _feature request_ via [Bugzilla](https://bugzilla.suse.com/enter_bug.cgi?format=guided&product=openSUSE%20Tumbleweed&component=YaST2), settings the `Severity` as _Enhancement: Request for new feature or enhancement_.?

Thanks!

**Comment by dgdavid** [comment]
BTW, you can use the [simplified registration](https://www.microfocus.com/selfreg/jsp/createSimpleAccount.jsp) if you don't have Bugzilla account yet.
